name: Deploy to digital ocean cluster
on:
  push:
    branches: ["master", "klausur"]
  pull_request:
    branches: ["master"]
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./deployment/ -n mikewaldenmaier
